# Fond & texte
background              #1a1814
foreground              #c8b89a
background_opacity      0.92
dynamic_background_opacity yes

# Curseur
cursor                  #8fa88c
cursor_text_color       #1a1814

# Sélection
selection_background    #2e2a24
selection_foreground    #c8b89a

# URL au survol
url_color               #7a8fa8

# Bords de fenêtre
active_border_color     #8fa88c
inactive_border_color   #2e2a24
bell_border_color       #a87d4a

# Onglets
active_tab_background   #2e2a24
active_tab_foreground   #8fa88c
inactive_tab_background #1a1814
inactive_tab_foreground #6b6257
tab_bar_background      #141210

# Noir
color0  #1a1814
color8  #3a342c

# Rouge
color1  #8a4a3c
color9  #a85a48

# Vert
color2  #8fa88c
color10 #a8c4a4

# Jaune / Ambre
color3  #a87d4a
color11 #c8a06a

# Bleu orageux
color4  #7a8fa8
color12 #9aaec8

# Mauve (violet désaturé)
color5  #8a7a98
color13 #a898b8

# Cyan canal
color6  #6a9890
color14 #8ab8b0

# Blanc cassé
color7  #c8b89a
color15 #e8d8ba
